spring:
  application:
    name: WorldsEdgeLink-API
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;LOCK_TIMEOUT=30000;DB_CLOSE_DELAY=-1;MODE=MySQL
    username: sa
    password:
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
      properties:
        hibernate:
          jdbc:
            batch_size: 100
            fetch_size: 100
            batch_versioned_data: true
          order_inserts: true
          order_updates: true

server:
  port: 8080